### ISSUE TITLE
 invalid choice: 'nat' 

### ISSUE THREAD

**Issue by ustcdane** [baoy-nlp/CNAT#1]
Hi, thanks for your great work!
I tried run train.py, but, I get the following error:
train.py: error: argument --task: invalid choice: 'nat' (choose from 'audio_pretraining', 'cross_lingual_lm', 'denoising', 'language_modeling', 'legacy_masked_lm', 'masked_lm', 'multilingual_denoising', 'multilingual_masked_lm', 'translation', 'multilingual_translation', 'semisupervised_translation', 'sentence_prediction', 'sentence_ranking', 'speech_to_text', 'translation_from_pretrained_bart', 'translation_from_pretrained_xlm', 'translation_lev', 'translation_multi_simple_epoch', 'dummy_lm', 'dummy_masked_lm', 'dummy_mt')

PyTorch == 1.8
fairseq==0.10.2

**Comment by baoy-nlp** [comment]
Can you share your fully training command here?  I suspect that you may not specify the correct path for user-dir.
If you run the ``python3 train.py --user-dir latent_nat ...'', you may correctly train the model.

**Comment by ustcdane** [comment]
> 
> 
> Can you share your fully training command here? I suspect that you may not specify the correct path for user-dir.
> If you run the ``python3 train.py --user-dir latent_nat ...'', you may correctly train the model.

@baoy-nlp  Thanks ,you are right, my user-dir path is wrong

**Comment by ustcdane** [comment]
hi, @baoy-nlp  I get another error :  ImportError: cannot import name 'flat' from 'latent_nat'   , is  glat input error to flat?

**Comment by baoy-nlp** [comment]
Please share your fully training command here without the detailed path?  I can run it in my local environment for more details.

**Comment by ustcdane** [comment]
> 
> 
> Please share your fully training command here without the detailed path? I can run it in my local environment for more details.

hi,  now I can run without error  when modify this line:https://github.com/baoy-nlp/CNAT/blob/7f270cff443db5dced048f7233f6a88b75075f0b/latent_nat/__init__.py#L4

from latent_nat import glat

**Comment by baoy-nlp** [comment]
Thanks for pointing out this.  I have fixed this typo.
