### ISSUE TITLE
Question about data preprocessing

### ISSUE THREAD

**Issue by speedcell4** [baoy-nlp/CNAT#4]
Hi.

You have mentioned that
> IWSLT14 German-English & WMT14 English-German: we mostly follow the instruction of the Fairseq.

Then I assume you used [this script](https://github.com/pytorch/fairseq/blob/75051ecf26239be1b082101b9d1fe8886e734b45/examples/translation/prepare-wmt14en2de.sh#L40-L47), and I noticed there is a `--icml17` flag. Did you use this flag when you pre-process the WMT14 English-German dataset? 
Sorry for this trivial question, but I just want to make sure my data preprocessing is the same as yours.

**Comment by baoy-nlp** [comment]
Yes. I use the --icml17 flag for preprocessing the  WMT14 English-German dataset.
